import { Story } from '@/types';

export const firstStory: Story = {
  id: 'synta-001-la-casa-que-empezo-a-olvidarnos',
  title: 'La casa que empezó a olvidarnos',
  subtitle: 'Primera historia de SYNTA',
  edition: 'SYNTA 001',
  genre: 'Ficción especulativa',
  readingTime: '30–40 min',
  wordCount: 3840,
  synopsis:
    'Una pareja. Una casa. Y algo que empieza a borrar silenciosamente todo lo que demuestra que estuvieron juntos.',
  authorNoteHidden: 'NOMA / SYNTA 001',
  chapters: [
    {
      id: 'capitulo-1',
      number: 'I',
      title: 'El marco de cal',
      paragraphs: [
        'La primera señal no tuvo ningún dramatismo. Ocurrió un martes de octubre, bajo esa luz oblicua y grisácea que entra en el cuarto piso de la calle Conde de Aranda justo antes de que enciendan las farolas.',
        'Clara estaba descalza, con el jersey gris de lana que solía quitarse en cuanto hervía el agua de la tetera. Pasó los dedos por la moldura del recibidor buscando las llaves de la bicicleta y se detuvo delante del pequeño marco de madera de haya. En ese marco, desde el segundo invierno que compartieron, había estado la fotografía tomada en la desembocadura del Tajo: Mateo de espaldas, con el cortavientos azul marino inflado por el viento atlántico, sosteniendo una libreta amarilla contra el pecho.',
        'El marco seguía allí, exactamente en el mismo clavo de latón, con el cristal limpio y sin una mota de polvo. Pero dentro del marco no había ninguna fotografía. Solo el paspartú de cartulina marfil y, detrás, el fondo rugoso de la pared pintada a la cal.',
        '—Mateo, ¿has movido la foto de Lisboa? —preguntó ella hacia el fondo del pasillo, sin levantar la voz.',
        'El rumor del agua en la cocina cesó un instante.',
        '—¿Cuál foto? —respondió él.',
        '—La de la orilla del río. La que tenía la mancha de café en la esquina izquierda.',
        'Mateo apareció en el dintel de la cocina secándose los nudillos con un paño de lino. Miró el marco con una calma que a Clara, por un segundo imperceptible, le pareció casi extranjera. Se acercó despacio, se inclinó un par de centímetros hacia el cristal y ladeó la cabeza.',
        '—Ese marco siempre ha estado vacío, Clara. Lo compramos en el Rastro para poner una lámina botánica que nunca llegamos a imprimir.',
        'Clara lo miró a los ojos. En el iris de Mateo no había ironía, ni distracción, ni ese juego infantil que a veces gastaban cuando escondían las novelas del otro en los estantes altos. Había únicamente la limpidez neutra de una certeza absoluta.',
        'Esa noche, mientras cenaban crema de calabaza en silencio, Clara apoyó los codos en la mesa de roble y cerró los párpados. En su memoria, el tacto del papel fotográfico era nítido: el borde cortado con guillotina manual, el peso del papel baritado de trescientos gramos, el olor a salitre y a revelador que Mateo había traído en una caja de zapatos desde Oporto. Sin embargo, al abrir los ojos y mirar el marco vacío al final del corredor, sintió por primera vez un frío minúsculo en la nuca: como si la habitación hubiera exhalado un aliento ajeno.',
      ],
    },
    {
      id: 'capitulo-2',
      number: 'II',
      title: 'La porcelana azul',
      paragraphs: [
        'Durante cuarenta y ocho horas no sucedió nada. La vida doméstica continuó con su fricción habitual: el zumbido del refrigerador viejo, las hojas secas del ficus que caían sobre la alfombra bereber, los correos de trabajo que se acumulaban en la pantalla de la portátil.',
        'El jueves por la mañana, Mateo bajó a comprar pan de centeno. Clara se quedó sola en la cocina preparando el café matutino. Abrió la alacena superior —esa que chirriaba en la bisagra izquierda desde la mudanza de 2021— y estiró la mano hacia la taza de cerámica esmaltada con un fino ribete azul cobalto. Era la taza en la que Mateo bebía cada día: ligeramente irregular, cocida en un taller de Alentejo, con una pequeña hendidura en la base donde encajaba con precisión el pulgar.',
        'La alacena tenía cinco tazas. Tres blancas de porcelana industrial y dos de barro cocido que pertenecían a la madre de Clara.',
        'No había ninguna taza con ribete azul cobalto.',
        'Clara sacó las tazas una a una, colocándolas sobre la encimera de granito con un cuidado milimétrico. Inspeccionó el fregadero. El lavavajillas. El escurridor de platos. Incluso abrió el cubo de la basura orgánica con un temblor absurdo en las yemas de los dedos, temiendo que Mateo la hubiera roto por accidente y ocultado los tiestos para evitar una discusión tonta.',
        'No había astillas. No había polvo de cerámica.',
        'Cuando la puerta blindada chasqueó y Mateo entró con la bolsa de papel crujiente bajo el brazo, Clara no se movió del centro de la cocina.',
        '—¿Dónde está tu taza, Mateo?',
        'Él dejó el pan sobre la tabla de madera, colgó la chaqueta en la percha y la miró desconcertado.',
        '—En el estante, supongo.',
        '—No está en el estante. Ni en el fregadero. Ni rota en la basura.',
        'Mateo se acercó a la encimera, tomó una de las tazas blancas genéricas, encendió la cafetera italiana con un fósforo y vertió la leche de avena.',
        '—Clara, siempre uso esta. Desde que nos mudamos aquí.',
        '—No usas esa. Esa taza la compramos en una tienda de artículos de oficina cuando vinieron mis primos en verano. Tú usas la de Alentejo, la que tiene el pulgar marcado en la base.',
        'Mateo la miró largamente. No con irritación, sino con esa paciencia compasiva que se reserva para quien empieza a mostrar signos de fatiga extrema o de fiebre.',
        '—Nunca hemos estado en Alentejo juntos, Clara. Te estás confundiendo con un viaje anterior.',
        'Las palabras cayeron sobre la baldosa hidráulica con la pesadez de una losa. Clara quiso rebatirlo: quiso recordar el hotel rural de paredes encaladas, la lluvia sobre los alcornoques, la noche en que el coche se quedó sin batería en una gasolinera desierta. Pero cuando intentó nombrar el pueblo exacto, la palabra se disolvió en su boca antes de llegar a la lengua. Era como intentar recordar el rostro de alguien visto a través de un cristal empañado por el vaho de un tren en marcha.',
      ],
    },
    {
      id: 'capitulo-3',
      number: 'III',
      title: 'El margen raspado',
      paragraphs: [
        'Esa tarde Clara no fue a su estudio. Se encerró en el despacho pequeño, el cuarto que daba al patio interior donde solo se escuchaban las tuberías y las palomas.',
        'En la tercera balda de la librería reposaban sus cuadernos de notas: siete libretas de tapas negras de tela japonesa, cosidas a mano, donde llevaba un diario discontinuo de lecturas y proyectos desde hacía diez años. Abrió la libreta de 2022, el año en que decidieron firmar el contrato de alquiler.',
        'Pasó las páginas con respiración contenida.',
        'En la página cuarenta y tres, donde ella recordaba haber anotado: «Mateo dice que la luz de las seis de la tarde parece miel derramada sobre los rodapiés», la línea de tinta estilográfica negra se interrumpía bruscamente tras la palabra «dice». A continuación había un espacio en blanco de cinco centímetros. El papel no estaba tachado con típex ni borrado con goma; simplemente las fibras del papel estaban lisas, vírgenes, como si la pluma se hubiera levantado en el aire y hubiera reanudado el trazo más adelante con una observación impersonal sobre el precio del metro cúbico de gas.',
        'Fue entonces cuando Clara comprendió que lo que estaba ocurriendo no era un olvido de Mateo. Tampoco era una pérdida de cordura suya.',
        'Era el espacio físico el que estaba ejecutando una poda silenciosa.',
        'El apartamento —las cuatro paredes, la tarima flotante, los rodapiés de pino, las juntas de silicona de las ventanas— estaba retrayendo su complicidad. Como un organismo vivo que decide que un huésped determinado nunca estuvo allí, la casa absorbía las huellas de Mateo con una prolijidad quirúrgica.',
        'Salió al pasillo. Mateo estaba sentado en el sofá de lino crudo leyendo una edición de bolsillo de Cesare Pavese. La luz de la ventana le recortaba el perfil: la nariz recta con una levísima desviación en el puente, la sombra de barba de dos días, el jersey de cuello vuelto que ella misma le había regalado por su trigésimo cumpleaños.',
        '—Mateo —susurró.',
        'Él levantó la vista del libro. Sus ojos eran oscuros, serenos, idénticos a los de siempre.',
        '—Dime, Clara.',
        '—¿Cuánto tiempo llevas viviendo aquí?',
        'Mateo sonrió con timidez, bajando el libro hacia sus rodillas.',
        '—Pues desde hace un par de semanas, ¿no? Desde que me ofreciste compartir el alquiler temporalmente mientras encuentro un piso cerca de la universidad.',
        'A Clara se le cortó el aire en la garganta. Cayó de rodillas sobre la alfombra.',
        'Nueve inviernos. Tres mudanzas compartidas. Las llaves conjuntas en el llavero de cuero con las iniciales entrelazadas. Reducidos a «un par de semanas».',
      ],
    },
    {
      id: 'capitulo-4',
      number: 'IV',
      title: 'La resonancia del pasillo',
      paragraphs: [
        'Durante la noche, Clara no durmió. Se quedó tendida de espaldas en la cama doble, con los ojos fijos en la pequeña grieta del techo que tenía la forma de un estuario.',
        'A su lado, Mateo respiraba con un compás acompasado. Pero cada vez que se movía, el colchón parecía registrar su peso con menor resistencia. Como si el cuerpo que dormía a su izquierda no pesara ya los setenta y cuatro kilos de un hombre adulto, sino la gravedad liviana de una sombra o de un abrigo dejado sobre las mantas.',
        'Clara extendió la mano derecha y rozó los dedos de Mateo. La piel estaba tibia, los nudillos ásperos por el frío otoñal. Pero al apretar con suavidad, la sensación no fue la de estrechar a su compañero de una década, sino la de tocar una fotografía que alguien va sumergiendo lentamente en agua caliente hasta que la emulsión comienza a resbalar del papel.',
        '—Si te vas de esta casa —le susurró Clara al oído, con una voz rota que apenas hizo vibrar las cortinas—, ¿adónde crees que vas?',
        'Mateo no despertó. Pero en su respiración hubo un descenso repentino, un silencio que duró tres latidos de más antes de reanudarse.',
        'A las cuatro de la madrugada, Clara se levantó. Caminó por el pasillo a oscuras. Se dio cuenta de que la acústica de la casa había cambiado por completo: donde antes cada paso producía un eco seco y familiar que reconocía los muebles de ambos, ahora el sonido rebotaba con la frialdad hueca de una vivienda recién desocupada.',
        'Fue al cuarto de baño. En el vaso de cristal sobre el lavabo solo había un cepillo de dientes.',
        'En el armario de la entrada, las dos perchas de madera donde solía colgar la gabardina de Mateo estaban desnudas, balanceándose con un roce metálico imperceptible.',
        'Clara corrió a su teléfono. Buscó en la agenda el contacto «Mateo». La letra M pasaba directamente de «Mamá» a «Marta Estudio».',
        'Abrió la galería de fotos del teléfono. Al deslizar el dedo hacia atrás en los álbumes de los últimos cinco años, las imágenes mostraban únicamente a Clara sola en terrazas frente al mar, Clara sonriendo delante de catedrales en ruinas, Clara sentada frente a mesas preparadas para dos comensales donde el segundo plato permanecía intacto y la silla de enfrente vacía.',
      ],
    },
    {
      id: 'capitulo-5',
      number: 'V',
      title: 'La geografía de la ausencia',
      paragraphs: [
        'El amanecer llegó sin colores, con una niebla densa que borraba las azoteas de los edificios vecinos.',
        'Mateo ya estaba levantado cuando Clara entró en el salón. Estaba de pie junto al ventanal, con las manos en los bolsillos del pantalón oscuro. La luz tamizada parecía atravesar los bordes de sus hombros con una transparencia vaporosa, como si estuviera hecho del mismo aire frío que empañaba los cristales.',
        '—Creo que hoy me marcharé, Clara —dijo él, sin volverse.',
        'Su voz ya no sonaba en el espacio con la densidad de un cuerpo. Sonaba como un pensamiento que cruza una habitación vacía.',
        '—No te vayas —suplicó ella, aferrándose al marco de la puerta—. Quédate aquí. Aunque la casa no te recuerde. Aunque las paredes digan que nunca estuviste. Yo me acuerdo. Yo me acuerdo de la cicatriz en tu rodilla, del olor a tomillo en tus dedos cuando cocinabas, del día que se nos cayó la lámpara de papel en el pasillo.',
        'Mateo se giró muy despacio. En su rostro no había dolor, ni reproche, ni tristeza. Había una aceptación tan serena y limpia que a Clara le dolió más que cualquier adiós violento.',
        '—El problema, Clara, no es que la casa me olvide a mí —dijo él con dulzura infinita—.',
        'Hizo una pausa breve. El reloj del salón dio las siete con un tañido metálico.',
        '—El problema es que la casa está recordando lo que realmente ocurrió antes de que construyeras este refugio.',
        'Clara sintió que el suelo bajo sus pies perdía firmeza. La alfombra, los estantes de cedro, las tazas de café, las ventanas... todo comenzó a reordenarse en su conciencia no como un presente indestructible, sino como una ficción delicadísima y desesperada que había sostenido durante meses para no enfrentarse al día en que Mateo cerró la maleta y subió al tren sin billete de vuelta.',
        '—¿Quién eres tú, entonces? —preguntó ella en un susurro que era casi un sollozo.',
        'Mateo sonrió con esa ternura vieja que solo tienen los amores que ya pertenecen al pasado.',
        '—Soy la última conversación que necesitabas tener con este cuarto piso antes de volver a dejar entrar la luz.',
      ],
    },
    {
      id: 'capitulo-6',
      number: 'VI',
      title: 'Lo que queda cuando la casa calla',
      paragraphs: [
        'A las ocho y media de la mañana, la niebla se retiró sobre los tejados de Madrid y un rayo limpio de sol otoñal cortó el salón en dos mitades simétricas.',
        'Clara estaba sentada en el suelo, con la espalda apoyada contra el rodapié de pino blanco. La casa estaba en completo silencio. No era el silencio amenazante de los días anteriores, sino el sosiego amplio de un lugar donde las cosas han vuelto a su peso justo.',
        'Miró el marco en la pared del recibidor. Seguía vacío. Pero ahora el vacío no parecía una mutilación, sino un claro abierto en el bosque: un espacio disponible para lo que todavía tiene que llegar.',
        'Se levantó, fue a la cocina y preparó una sola taza de café en la loza blanca. Abrió la ventana de par en par. El aire frío de la mañana le llenó el pecho de una frescura que creía perdida desde hacía mucho tiempo.',
        'Comprendió entonces algo que ninguna filosofía le había enseñado: olvidar no es el borrado cruel de lo vivido, sino la forma en que los lugares que habitamos nos devuelven suavemente al mundo cuando ya no podemos seguir viviendo dentro de un recuerdo.',
        'Bebió el café a pequeños sorbos, de pie junto a la ventana abierta, mientras la ciudad allá abajo despertaba con su rumor eterno de motores, pasos y comienzos.',
      ],
    },
  ],
};
